kotlin.code.style=official
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
kotlin.stdlib.default.dependency=false

group = dev.kikugie
version = 0.9-alpha.0