[versions]
# Kotlin
kotlin-jvm = { strictly = "2.1.20" }
kotlin-ksp = { strictly = "2.1.20-1.0.32" }
kotlin-dokka = { strictly = "2.0.+" }
kotlin-validator = { strictly = "0.17.+" }
kotlin-serialization = { prefer = "1.8.+" }
kotlin-coroutines = { prefer = "1.10.+" }
kotlin-datetime = { prefer = "0.6.+" }

# Gradle
gradle-shadow = { strictly = "[9.0.0-beta4,9.1)" }
gradle-publish = { prefer = "1.+", strictly = "[1.2,)" }

# Testing
testing-junit = { prefer = "5.+", strictly = "[5.9, 6.0)" }
testing-kotest = { prefer = "5.+", strictly = "[5.9, 6.0)" }

# Miscellaneous
extra-kdoclink = { strictly = "0.+" }
extra-mordant = { prefer = "3.+" }
extra-kaml = { prefer = "0.+" }
extra-text = { prefer = "1.12.+" }
extra-okhttp = { prefer = "4.12.+", strictly = "[4,)" }

[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp"}
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
kotlin-dokka-javadoc = { id = "org.jetbrains.dokka-javadoc" }
kotlin-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-validator" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-jvm" }

# Gradle
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
gradle-shadow = { id = "com.gradleup.shadow", version.ref = "gradle-shadow" }

# Miscellaneous
extra-kdoclink = { id = "dev.kikugie.kdoclink", version.ref = "extra-kdoclink" }

[libraries]
# Kotlin
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "kotlin-coroutines" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core-jvm", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "kotlin-serialization" }
kotlin-serialization-yaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "extra-kaml" }

# Testing
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "testing-junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "testing-junit" }
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "testing-kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "testing-kotest" }
kotest-datatest = { group = "io.kotest", name = "kotest-framework-datatest-jvm", version.ref = "testing-kotest" }
kotest-property = { group = "io.kotest", name = "kotest-property-jvm", version.ref = "testing-kotest" }

# Miscellaneous
extra-mordant = { group = "com.github.ajalt.mordant", name = "mordant", version.ref = "extra-mordant" }

[bundles]
stonecutter = [
    "kotlin-coroutines",
    "kotlin-serialization",
    "kotlin-serialization-json",
    "kotlin-serialization-yaml",
]

stitcher = [
    "kotlin-serialization"
]

test = [
    "kotest-runner",
    "kotest-assertions",
    "kotest-datatest"
]