repositories:
  excluded_owners:
    - stonecutter-versioning
  disallowed_words:
    - stonecutter
    - template
    - example
entries:
  - id: 0mods/ECR
    curseforge: /EXCLUDED/
  - id: Anime-pdf/i-cant-do-math
    curseforge: https://www.curseforge.com/minecraft/mc-mods/i-cant-do-math
  - id: Chailotl/inventory-sort
    modrinth: https://modrinth.com/mod/chais-inventory-sorter
  - id: Crendgrim/DynamicCrosshairCompat
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dynamic-crosshair-compat
  - id: Danrus1100/DRHud
    modrinth: /EXCLUDED/
  - id: DuperKnight/DuperAutoWalk
    modrinth: https://modrinth.com/mod/autowalker
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dupers-autowalk
  - id: Faboslav/it-takes-a-pillage
    curseforge: https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage-continuation
  - id: IMB11/ExtraShields
    curseforge: https://www.curseforge.com/minecraft/mc-mods/extra-shields
  - id: IMB11/MRU
    curseforge: https://www.curseforge.com/minecraft/mc-mods/mru
  - id: IMB11/SkinShufflePlugin
    valid: false
  - id: IMB11/Sounds
    curseforge: https://www.curseforge.com/minecraft/mc-mods/sound
  - id: Imajo24I/Mob-Armor-Trims
    curseforge: https://www.curseforge.com/minecraft/mc-mods/mob-armor-trims
  - id: Lemonnik6484/BetterWalls
    curseforge: https://www.curseforge.com/minecraft/mc-mods/better-walls
  - id: LopyMine/Fast-Recipe
    curseforge: https://www.curseforge.com/minecraft/mc-mods/fast-recipe
  - id: Mirsario/Minecraft-CameraOverhaul
    modrinth: https://modrinth.com/mod/cameraoverhaul
    curseforge: https://www.curseforge.com/minecraft/mc-mods/cameraoverhaul
  - id: MisterCheezeCake/SkyblockTweaks
    modrinth: https://modrinth.com/mod/sbt
  - id: ProunceDev/BetterCooldownsHUD
    modrinth: https://www.curseforge.com/minecraft/mc-mods/bettercooldownshud
  - id: Raik176/better-saved-tabs
    curseforge: https://www.curseforge.com/minecraft/mc-mods/better-saved-tabs
  - id: Raik176/datapack-utils
    curseforge: https://www.curseforge.com/minecraft/mc-mods/datapack-utils
  - id: Raik176/detail-armor-bar-compat
    curseforge: https://www.curseforge.com/minecraft/mc-mods/detailab-compat
  - id: RedRain0o0/legacy-skins
    curseforge: https://www.curseforge.com/minecraft/mc-mods/legacy-skins
  - id: Wilyicaro/FactoryAPI
    curseforge: https://www.curseforge.com/minecraft/mc-mods/factory-api
  - id: anastarawneh/MCCINametagMod
    modrinth: https://modrinth.com/mod/mcc-island-nametag-mod
  - id: cassiancc/Item-Descriptions
    curseforge: https://www.curseforge.com/minecraft/mc-mods/item-descriptions
  - id: enjarai/cicada-lib
    modrinth: https://modrinth.com/mod/cicada
    curseforge: https://www.curseforge.com/minecraft/mc-mods/cicada
  - id: enjarai/shared-resources
    curseforge: https://www.curseforge.com/minecraft/mc-mods/shared-resources
  - id: isXander/YetAnotherConfigLib
    modrinth: https://www.curseforge.com/minecraft/mc-mods/yacl
  - id: isXander/opti-painting
    curseforge: https://www.curseforge.com/minecraft/mc-mods/optipainting
  - id: lvoegl/analogmovement-mc
    modrinth: https://modrinth.com/mod/analogmovement
    curseforge: https://www.curseforge.com/minecraft/mc-mods/analogmovement
  - id: meza/Disable-Christmas-Chests
    curseforge: https://www.curseforge.com/minecraft/mc-mods/disablechristmaschests
  - id: meza/ServerRedstoneBlock
    curseforge: https://www.curseforge.com/minecraft/mc-mods/server-redstone-block
  - id: nvb-uy/OffHandTickFix
    curseforge: https://www.curseforge.com/minecraft/mc-mods/off-hand-tick-fix
  - id: pajicadvance/simple-death-improvements
    curseforge: https://www.curseforge.com/minecraft/mc-mods/simple-death-improvements
  - id: pajicadvance/simple-smithing-overhaul
    curseforge: https://www.curseforge.com/minecraft/mc-mods/simple-smithing-overhaul
  - id: plasmoapp/pv-addon-discs
    modrinth: https://modrinth.com/plugin/pv-addon-discs
  - id: txnimc/DoesItTickSC
    modrinth: https://modrinth.com/mod/does-it-tick
    curseforge: https://www.curseforge.com/minecraft/mc-mods/does-it-tick
  - id: txnimc/ImmersiveMessages
    modrinth: https://modrinth.com/mod/immersive-messages-api
    curseforge: https://www.curseforge.com/minecraft/mc-mods/immersive-messages-api
  - id: txnimc/PronounMC
    curseforge: https://www.curseforge.com/minecraft/mc-mods/pronounmc
  - id: txnimc/SodiumDynamicLights
    curseforge: https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged
  - id: txnimc/SodiumOptionsModCompat
    curseforge: https://www.curseforge.com/minecraft/mc-mods/sodium-embeddium-options-mod-compat
  - id: txnitxnichopper/PronounMC
    curseforge: https://www.curseforge.com/minecraft/mc-mods/pronounmc
  - id: MicrocontrollersDev/Confirm-Disconnect
    source: https://codeberg.org/MicrocontrollersDev/Confirm-Disconnect
  - id: MicrocontrollersDev/Smooth-Skies
    source: https://codeberg.org/MicrocontrollersDev/Smooth-Skies
  - id: MicrocontrollersDev/CrosshairTweaks
    source: https://codeberg.org/MicrocontrollersDev/CrosshairTweaks
  - id: MicrocontrollersDev/ScoreboardTweaks
    source: https://codeberg.org/MicrocontrollersDev/ScoreboardTweaks
  - id: MicrocontrollersDev/NametagTweaks
    source: https://codeberg.org/MicrocontrollersDev/NametagTweaks
  - id: MicrocontrollersDev/OverlayTweaks
    source: https://codeberg.org/MicrocontrollersDev/OverlayTweaks
  - id: MicrocontrollersDev/TitleTweaks
    source: https://codeberg.org/MicrocontrollersDev/TitleTweaks
  - id: MicrocontrollersDev/BetterNightVision
    source: https://codeberg.org/MicrocontrollersDev/BetterNightVision
  - id: MicrocontrollersDev/TabTweaks
    source: https://codeberg.org/MicrocontrollersDev/TabTweaks
  - id: MicrocontrollersDev/DroppedItemTweaks
    source: https://codeberg.org/MicrocontrollersDev/DroppedItemTweaks
  - id: MicrocontrollersDev/Sciophobia
    source: https://codeberg.org/MicrocontrollersDev/Sciophobia
  - id: MicrocontrollersDev/ScrollTweaks
    source: https://codeberg.org/MicrocontrollersDev/ScrollTweaks
  - id: MicrocontrollersDev/MountOpacity
    source: https://codeberg.org/MicrocontrollersDev/MountOpacity
  - id: KyrptonaughtMC/Inventory-Sorter
    modrinth: https://modrinth.com/mod/inventory-sorting
    curseforge: https://www.curseforge.com/minecraft/mc-mods/inventory-sorting
