when:
  event: push
  branch: "0.6"

steps:
  run-dokka:
    image: gradle:jdk17-corretto
    commands:
      - gradle dokkaGeneratePublicationHtml --no-daemon
  move-files:
    image: alpine/git
    commands:
      - git clone https://codeberg.org/stonecutter/docs.git docs
      - mkdir -p docs/docs/public/dokka
      - rm -rf docs/docs/public/dokka/*
      - cp -r build/dokka/html/* docs/docs/public/dokka/
      - >-
        if git diff-index --quiet HEAD; then
          echo "SKIP_PUSH=true" >> envvars;
          echo "Nothing changed...";
        fi
  push-changes:
    image: appleboy/drone-git-push
    when:
      evaluate: SKIP_PUSH != true
    directory: docs
    settings:
      ssh-key:
        from_secret: CB_PUSH
      remote: ssh://git@codeberg.org/stonecutter/docs.git
      branch: main
      commit: true
      commit_message: "Update dokka from ${CI_PIPELINE_FORGE_URL}"
      author_name: stonecutter-runner
      author_email: kikugie@noreply.codeberg.org