when:
  event: push
  branch: 0.*
  path:
    exclude: ["tools/**"]

steps:
  run-dokka:
    image: gradle:jdk17-corretto
    commands:
      - gradle dokkaGeneratePublicationHtml --no-daemon -Dorg.gradle.configuration-cache.read-only=true
  clone-pages:
    image: alpine/git
    commands:
    - git clone --depth 1 https://codeberg.org/stonecutter/docs.git docs
    - git lfs fetch
    - git lfs checkout
  zip-files:
    image: ubuntu
    commands:
      - mkdir -p docs/setup/dokka
      - rm -f "docs/setup/dokka/${CI_COMMIT_BRANCH}.tar.gz"
      - tar czvf docs/setup/dokka/${CI_COMMIT_BRANCH}.tar.gz -C build/dokka/html .
  push-changes:
    image: appleboy/drone-git-push
    directory: docs
    settings:
      ssh-key:
        from_secret: CB_PUSH
      remote: ssh://git@codeberg.org/stonecutter/docs.git
      branch: main
      commit: true
      commit_message: Update dokka from ${CI_PIPELINE_FORGE_URL}
      author_name: stonecutter-runner
      author_email: kikugie@noreply.codeberg.org